release: main.cpp QuadraticEquation.cpp common.cpp
	g++ main.cpp QuadraticEquation.cpp common.cpp

debug: main.cpp QuadraticEquation.cpp common.cpp tests.cpp
	g++ main.cpp QuadraticEquation.cpp common.cpp tests.cpp -DDEBUG