release: 
	g++ -DNDEBUG main.cpp common.cpp QuadraticEquation.cpp tests.cpp 

debug:
	g++ main.cpp common.cpp QuadraticEquation.cpp tests.cpp 

main.o: main.cpp
	g++ c main.cpp

common.o: common.cpp
	g++ c common.cpp

QuadraticEquation.o: QuadraticEquation.cpp
	g++ c QuadraticEquation.cpp

tests.o: tests.cpp
	g++ c tests.cpp